### ISSUE TITLE
Is there a list of all the ADB commands you wrap in this app?

### ISSUE THREAD

**Issue by puterboy** [joaomgcd/Tasker-Permissions#20]
For me, it's easier just to run a shell script on my Linux box that runs the required ADB commands rather than having to install an entire package.

Assuming this app is just a wrapper for ADB commands as you mention in the README, would it be possible to share them in text form?

Thanks!!!

**Comment by joaomgcd** [comment]
Hi. Does this file help? :)

https://github.com/joaomgcd/Tasker-Permissions/blob/main/app/adbpermission/adbpermissions.js

**Comment by puterboy** [comment]
Thanks :)
Unfortunately I don't really know Java so not sure how to translate this into a bash-like shell script...
I had hoped there would just be a series of simple adb shell commands like:

`adb shell pm grant net.dinglisch.android.taskerm android.permission.WRITE_SECURE_SETTINGS
`
which I ran to get the "Key Accessibility Enabled" profile working as per
[https://tasker.joaoapps.com/userguide/en/help/ah_secure_setting_grant.html](url)

**Comment by joaomgcd** [comment]
Basically all permissions that say "isPmGrant: true" on that page you can use with the same command as the example you posted :)

if it's not a pm grant the use "appops set" instead but instead of "grant" use "allow"

The permissions are listed on that page on each line that says "permission: PERMISSION_NAME_HERE".

Does this help? 😅

**Comment by joaomgcd** [comment]
Because they are able to be granted through normal Android UI so I decided to not include them :)

Thank you very much for the list!
